// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
const spec_identifier = {__proto__:null,namespace:8, expr:16, map:50}
export const parser = Parser.deserialize({
  version: 13,
  states: ")xQYQPOOOeQPO'#C_OjQPO'#CcOoQQO'#CtOOQO'#C}'#C}OOQO'#Cv'#CvQYQPOOOOQO'#Ca'#CaOtQQO,58yOOQO'#Ce'#CeOyQPO,58}O!hQPO,59`OOQO-E6t-E6tOOQO1G.e1G.eOOQO'#Cf'#CfO!oQQO'#CgO!tQQO'#CiO!yQQO'#CkO#OQQO'#CmO#TQPO'#CnO#YQQO'#CpO#bQQO'#CrOOQO'#DR'#DRO#jQPO'#DPO$UQPO'#DPOOQO1G.i1G.iOOQO1G.z1G.zO$pQQO1G.zOOQO,59R,59ROOQO,59T,59TOOQO,59V,59VO$uQPO,59XO$zQQO,59YO%PQPO'#CqO%[QPO'#DVO%dQPO,59[O%iQQO'#CsO%tQPO'#D[O%|QPO,59^O$UQPO'#CyO&RQPO,59kO&RQPO,59kOyQPO7+$fOOQO1G.s1G.sO&mQPO1G.tOyQPO,59]O&rQQO,59qO&zQPO,59qOOQO1G.v1G.vOyQPO,59_O'SQQO,59vO'[QPO,59vOOQO1G.x1G.xOOQO,59e,59eOOQO-E6w-E6wO'dQPO1G/VOOQO<<HQ<<HQOOQO7+$`7+$`OOQO1G.w1G.wOOQO,59c,59cO(OQQO1G/]OOQO-E6u-E6uOOQO1G.y1G.yOOQO,59d,59dO(WQQO1G/bOOQO-E6v-E6vP(`QQO'#CwP(eQQO'#Cx",
  stateData: "(j~OpOSPOS~OSPOWQOiRO~OrVO~OrXO~OUZO~OU]O~O[_O^`O`aOccOr^OthOvbOxdO}eO~O!RkO~PyOUlO~OUmO~OUnO~OUoO~OvpO~OUqO|yP~OUtO!Q!OP~OtwOSsXWsXisXnsX{sX|sX!QsX~O[_O^`O`aOccOr^OvbOxdO}eO~OUzO~Ow{O~OU|O~Oz}O{eX|eX~O{!OO|yX~O|!QO~O!P!RO{gX!QgX~O{!SO!Q!OX~O!Q!UO~OtwOSsaWsaisansa{sa|sa!Qsa~Ow!ZO~OUqO|ya~O{!^O|ya~OUtO!Q!Oa~O{!bO!Q!Oa~OtwOSsiWsiisinsi{si|si!Qsi~OUqO|yi~OUtO!Q!Oi~OUqO~OUtO~O",
  goto: "$Z!PPPP!QP!UP!QP!X![![P![P![P![![P![!e![!m!QP!u!{#R#XPPP#cP#gP#vPPP$TPPPP$WTSOURWPRYQ_fYZhwz}!RQrdV!]!O!^!dQueV!a!S!b!eQUOR[UQ!PrR!_!PQ!TuR!c!TQxgS!Wx!XR!XyTTOUQiYQjZQ!YzQ![}R!`!RYgYZz}!RQyhR!VwRsdRve",
  nodeNames: "⚠ Comment Mapping Namespace namespace Prefix Term Expr expr ExprName Variable Dereference Pointer Projection Projector Injection Injector Identifier Constant String Tuple Slot Match Case Map map",
  maxTerm: 49,
  nodeProps: [
    [NodeProp.group, -8,10,11,13,15,17,18,20,22,"Expression"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: ")Q~RkX^!vpq!vrs#kst%wz{&S}!O&X!P!Q&d![!]&i!]!^&t!^!_&y!`!a'O!c!}']!}#O(b#O#P(g#P#Q(l#T#o']#o#p(q#p#q(v#q#r({#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~!{Yp~X^!vpq!v#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~#nUpq#kqr#krs$Qs#O#k#O#P$V#P~#k~$VOc~~$YXrs#k!P!Q#k#O#P#k#U#V#k#Y#Z#k#b#c#k#f#g#k#h#i#k#i#j$u~$xR!Q![%R!c!i%R#T#Z%R~%UR!Q![%_!c!i%_#T#Z%_~%bR!Q![%k!c!i%k#T#Z%k~%nR!Q![#k!c!i#k#T#Z#k~%|QP~OY%wZ~%w~&XO[~~&[P!`!a&_~&dOz~~&iO^~~&lP![!]&o~&tO!R~~&yO{~~'OOv~R'TPwP}!O'WQ']O!PQR'dSUQrP!Q![']![!]'p!c!}']#T#o']Q'uXUQst'p}!O'p!O!P'p!P!Q'p!Q!['p![!]'p!c!}'p#R#S'p#T#o'p~(gO}~~(lO`~~(qO!Q~~(vOx~~({Ot~~)QO|~",
  tokenizers: [0, 1],
  topRules: {"Mapping":[0,2]},
  specialized: [{term: 34, get: value => spec_identifier[value] || -1}],
  tokenPrec: 0
})
